### ISSUE TITLE
Add travis CI support

### ISSUE THREAD

**Issue by tracyone** [liuchengxu/space-vim#41]
[travis-ci](https://travis-ci.org)

You can use following vim lint tool to check viml:

[Kuniwak/vint](https://github.com/Kuniwak/vint)

[syngan/vim-vimlint](https://github.com/syngan/vim-vimlint)

[ynkdir/vim-vimlparser](https://github.com/ynkdir/vim-vimlparser)

.travis.yml example:

```yml
language: python

cache:
  pip: true

env:
  matrix:
    - LINT=vimlint-errors
    - LINT=vimlint
    - LINT=vint-errors
    - LINT=vint

matrix:
  allow_failures:
    - env: LINT=vimlint
    - env: LINT=vint

install:
  - |
    if [ "${LINT#vimlint}" != "$LINT" ]; then
      git clone --depth=1 https://github.com/syngan/vim-vimlint /tmp/vimlint
      git clone --depth=1 https://github.com/ynkdir/vim-vimlparser /tmp/vimlparser
    elif [ "${LINT#vint}" != "$LINT" ]; then
      virtualenv /tmp/vint && source /tmp/vint/bin/activate && pip install vim-vint
    fi
script:
  - |
    if [ "$LINT" = "vimlint" ]; then
      sh /tmp/vimlint/bin/vimlint.sh -l /tmp/vimlint -p /tmp/vimlparser .
    elif [ "$LINT" = "vimlint-errors" ]; then
      sh /tmp/vimlint/bin/vimlint.sh -E -l /tmp/vimlint -p /tmp/vimlparser .
    elif [ "$LINT" = "vint" ]; then
      vint .
    elif [ "$LINT" = "vint-errors" ]; then
      vint --error .
    fi

```
